/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Before;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.Reader;

import static org.junit.Assert.*;

public class AppTest {
    FileQuotes quote;
    FileQuotes emptyQuote;
    @Before
    public void setUp() throws Exception {
        quote = new FileQuotes();
        quote.author = "Ron Swanson";
        quote.text = "I wanna punch you in the face so bad right now.";

        emptyQuote = new FileQuotes();
    }

    @Test
    public void testToString() {
        System.out.println(quote);
        assertEquals("Quote should show author and then text.", "Author: Ron Swanson Quote: I wanna punch you in the face so bad right now.", quote.toString());
    }

    @Test
    public void testToString_emptyInstance() {
        System.out.println(emptyQuote);
        assertEquals("empty quote should just be Author: __ Quote: __ ", "Exception. Empty String", emptyQuote.toString());
    }


    @Test
    public void isInternetOnline() {
    }
}