/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import javax.print.DocFlavor;
import java.io.*;
import java.net.*;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Gson gson = new Gson();
        try {
            // https://www.baeldung.com/java-http-request
            URL url = new URL("http://ron-swanson-quotes.herokuapp.com/v2/quotes");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            System.out.println(connection.getResponseCode());

            BufferedReader input = new BufferedReader((new InputStreamReader(connection.getInputStream())));
            String inputLine;
            StringBuilder content = new StringBuilder();

            while ((inputLine = input.readLine()) != null) {
                content.append(inputLine);
            }
            input.close();
            System.out.println(content);
            writeQuotesToFile(content);
        } catch (FileNotFoundException e) {
            System.out.println("error reading file");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public static void writeQuotesToFile(StringBuilder quoteString) {
        BufferedWriter writer;
        try{
            writer = new BufferedWriter(new FileWriter(("src/main/resources/swansonQuotes.json")));
            writer.write(String.valueOf(quoteString));
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
     public boolean isInternetOnline() throws UnknownHostException {
        //returns true if offline, false if internet is connected.
        boolean output = !( "127.0.0.1"
                .equals(InetAddress
                        .getLocalHost()
                        .getHostAddress() ) );
        return output;
    }
}
