/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws IOException {
        printQuote(createArrayOfString());
    }

    public static Quote[] createArrayOfString() throws FileNotFoundException {
        Gson gson = new Gson();

        Scanner reader = new Scanner(new File("src/main/resources/recentQuotes.json"));
        StringBuilder quoteString = new StringBuilder();

        while (reader.hasNextLine()) {
            String lines = reader.nextLine();
            quoteString.append(lines);
        }
        String stringObjToString = quoteString.toString();
        Quote[] arrayOfQuotes = gson.fromJson(stringObjToString, Quote[].class);
        return arrayOfQuotes;
    }

    public static int quoteRandomizer(Quote[] arrayOfQuotes) {
       return (int)(Math.random() * arrayOfQuotes.length);
    }

    public static String printQuote (Quote[] arrayOfQuotes) {
        System.out.println(arrayOfQuotes[quoteRandomizer(arrayOfQuotes)].toString());
        return arrayOfQuotes[quoteRandomizer(arrayOfQuotes)].toString();

    }

}
